### ISSUE TITLE
polyPointsShortcuts is null

### ISSUE THREAD

**Issue by maxvipon** [vaseker/tzwhere#8]
``` shell
[18/Aug/2015:15:43:21 +0300] root:server [14535] sent 503 on GET /foobar?lat=41.006611&lon=28.978200 Reason: Cannot read property '41' of null
[18/Aug/2015:15:43:21 +0300] root:server [14535] TypeError: Cannot read property '41' of null
    at EventEmitter.tzNameNear (/foobar/node_modules/tzwhere/lib/index.js:349:41)
    at EventEmitter.tzInfo (/foobar/node_modules/tzwhere/lib/index.js:371:25)
    at EventEmitter.tzInfo (/foobar/node_modules/tzwhere/lib/index.js:401:18)
    at new Tz (/foobar/lib/times.js:35:21)
    at /foobar/controllers/forecast.js:50:25
```

**Comment by vaseker** [comment]
This is a sad mistake because of shortcuts caching: shortcuts for tzNear aren't cached and aren't reloaded.
